# Generated by Django 4.1 on 2022-09-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wordSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('output', models.CharField(max_length=12)),
                ('date', models.DateField()),
            ],
        ),
    ]
