# Generated by Django 4.1 on 2022-09-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_wordsentiment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsentiment',
            name='text',
            field=models.TextField(error_messages={'required': 'Please Enter the Text'}),
        ),
    ]
